/* SPDX-License-Identifier: GPL-3.0-only */
static const struct { const char *input, *expected; } text_line_cases[] = {
    {"Downloading 1%\rDownloading 25%\rDownloading 100%\r\n", "Downloading 100%\n"},
    {"10%\n20%\r\n100%\n", "10%\n20%\n100%\n"},
    {"abcdef\rxy\n", "xycdef\n"},
    {"Downloading 25%\r\x1b[KDone\n", "Done\n"},
    {"long progress\rOK\x1b[0K\n", "OK\n"},
    {"abc\x1b[2KX\n", "   X\n"},
    {"abc\r\x1b[2KX\n", "X\n"},
    {"abc\x1b[2G\x1b[1KX\n", " Xc\n"},
    {"\x1b[1K\n", "\n"},
    {"abc\x1b[2DX\x1b[CY\n", "aXcY\n"},
    {"abc\x1b[GX\x1b[3`Z\n", "XbZ\n"},
    {"abc\b\bXY\n", "aXY\n"},
    {"\b|\b/\b-\b\\\n", "\\\n"},
    {"10%\r\x1b[32m20%\x1b[0m\x1b[K\r\n", "20%\n"},
    {"10%\x1b]0;title\a\r20%\x1b]0;title\x1b\\\n", "20%\n"},
    {"10%\r\x1b[?25l20%\x1b[?25h\n", "20%\n"},
    {"中文abc\r好X\x1b[K\n", "好X\n"},
    {"中文abc\b\b\b\bX\n", "中Xabc\n"},
    {"中文abc\x1b[2G\x1b[1KX\n", " Xabc\n"},
    {"中文\x1b[2KX\n", "  X\n"},
    {"中文\x1b[1KX\n", "  X\n"},
    {"中文\x1b[2C\x1b[1KX\n", "    X\n"},
    {"ERROR 10%\rINFO 100%\x1b[K\n", "INFO 100%\n"},
};
