include(GNUInstallDirs)
include(CTest)
if(APPLE)
  link_libraries("-framework IOKit" "-framework CoreFoundation")
endif()
find_package(PkgConfig REQUIRED)
find_package(Gettext REQUIRED)
find_package(Python3 REQUIRED COMPONENTS Interpreter)
pkg_check_modules(GTK4 REQUIRED IMPORTED_TARGET gtk4>=4.12)
pkg_check_modules(PCRE2 REQUIRED IMPORTED_TARGET libpcre2-8)
set(NATIVE_MAIN src/serial_windows_main.c)
set(NATIVE_TOOLS)
if(NOT WIN32)
  set(NATIVE_MAIN src/serial_main.c)
  find_package(Intl REQUIRED)
  link_libraries(Intl::Intl)
  pkg_check_modules(VTERM REQUIRED IMPORTED_TARGET vterm>=0.3)
  link_libraries(PkgConfig::VTERM)
  pkg_check_modules(JSON_GLIB REQUIRED IMPORTED_TARGET json-glib-1.0>=1.6)
  set(NATIVE_PLUGIN src/plugin.c)
  if(APPLE)
    set(NATIVE_PLUGIN src/plugin_macos.c)
  endif()
  set(NATIVE_TOOLS src/native_terminal.c src/modbus.c src/modbus_ui.c src/native_i18n.c src/serial_format.c src/native_bridge.c src/transfer.c src/sequence.c src/quick_presets.c src/capture.c src/log_model.c src/analyzer.c src/plugin_ui.c ${NATIVE_PLUGIN})
  if(APPLE)
    list(APPEND NATIVE_TOOLS src/macos_window.c)
  endif()
  link_libraries(PkgConfig::JSON_GLIB)
endif()
add_executable(tio-gui WIN32 MACOSX_BUNDLE ${NATIVE_TOOLS}
  ${NATIVE_MAIN} src/native_serial.c src/highlighter.c src/payload.c src/settings.c)
target_link_libraries(tio-gui PRIVATE PkgConfig::GTK4 PkgConfig::PCRE2 )
if(WIN32)
  pkg_check_modules(NATIVE_PANGO REQUIRED IMPORTED_TARGET pango>=1.56)
  target_link_libraries(tio-gui PRIVATE advapi32 PkgConfig::NATIVE_PANGO)
  if(TIO_GUI_WINDOWS_ICON_RC)
    enable_language(RC)
    target_sources(tio-gui PRIVATE "${TIO_GUI_WINDOWS_ICON_RC}")
  endif()
endif()
if(APPLE)
  target_link_options(tio-gui PRIVATE -Wl,-headerpad_max_install_names)
endif()
foreach(language zh_CN)
  set(mo "${CMAKE_CURRENT_BINARY_DIR}/locale/${language}/LC_MESSAGES/tio-gui.mo")
  add_custom_command(OUTPUT "${mo}"
    COMMAND ${CMAKE_COMMAND} -E make_directory "${CMAKE_CURRENT_BINARY_DIR}/locale/${language}/LC_MESSAGES"
    COMMAND ${GETTEXT_MSGFMT_EXECUTABLE} --check -o "${mo}" "${CMAKE_CURRENT_SOURCE_DIR}/po/${language}.po"
    DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/po/${language}.po" VERBATIM)
  list(APPEND native_catalogs "${mo}")
  install(FILES "${mo}" DESTINATION "${CMAKE_INSTALL_LOCALEDIR}/${language}/LC_MESSAGES")
endforeach()
add_custom_target(native-translations ALL DEPENDS ${native_catalogs})
set(native_catalog "${CMAKE_CURRENT_BINARY_DIR}/native_catalog.h")
add_custom_command(OUTPUT "${native_catalog}"
  COMMAND ${Python3_EXECUTABLE} "${CMAKE_CURRENT_SOURCE_DIR}/scripts/native-catalog.py"
    "${CMAKE_CURRENT_BINARY_DIR}/locale/zh_CN/LC_MESSAGES/tio-gui.mo" "${native_catalog}"
  DEPENDS ${native_catalogs} "${CMAKE_CURRENT_SOURCE_DIR}/scripts/native-catalog.py" VERBATIM)
add_custom_target(native-catalog DEPENDS "${native_catalog}")
include_directories("${CMAKE_CURRENT_BINARY_DIR}")
add_dependencies(tio-gui native-catalog)
target_compile_definitions(tio-gui PRIVATE TIO_NATIVE_I18N TIO_GUI_VERSION="${PROJECT_VERSION}")
target_compile_options(tio-gui PRIVATE $<$<C_COMPILER_ID:GNU,Clang,AppleClang>:-Wall;-Wextra;-Wpedantic>)
set_target_properties(tio-gui PROPERTIES
  MACOSX_BUNDLE_BUNDLE_NAME "tio-gui"
  MACOSX_BUNDLE_GUI_IDENTIFIER "io.github.keithxc.tio_gui.serial"
  MACOSX_BUNDLE_BUNDLE_VERSION "${PROJECT_VERSION}"
  MACOSX_BUNDLE_SHORT_VERSION_STRING "${PROJECT_VERSION}")
install(TARGETS tio-gui RUNTIME DESTINATION bin BUNDLE DESTINATION .)
if(BUILD_TESTING)
  add_executable(native-serial-test tests/native_serial_test.c src/native_serial.c)
  target_include_directories(native-serial-test PRIVATE src)
  target_link_libraries(native-serial-test PRIVATE PkgConfig::GTK4)
  if(WIN32)
    target_link_libraries(native-serial-test PRIVATE advapi32)
  endif()
  add_test(NAME native-serial COMMAND native-serial-test)
  set_tests_properties(native-serial PROPERTIES TIMEOUT 30)
  add_executable(payload-test tests/payload_test.c src/payload.c)
  target_include_directories(payload-test PRIVATE src)
  target_link_libraries(payload-test PRIVATE PkgConfig::GTK4)
  add_test(NAME payload COMMAND payload-test)
  add_executable(highlighter-test tests/highlighter_test.c src/highlighter.c)
  target_include_directories(highlighter-test PRIVATE src)
  target_link_libraries(highlighter-test PRIVATE PkgConfig::GTK4)
  add_test(NAME highlighter COMMAND highlighter-test)
  if(NOT WIN32)
    add_executable(serial-ui-test ${NATIVE_TOOLS} tests/serial_ui_test.c src/native_serial.c src/highlighter.c src/payload.c src/settings.c)
    add_dependencies(serial-ui-test native-catalog)
    target_include_directories(serial-ui-test PRIVATE src)
    target_compile_definitions(serial-ui-test PRIVATE TIO_NATIVE_I18N TIO_GUI_VERSION="${PROJECT_VERSION}")
    target_link_libraries(serial-ui-test PRIVATE PkgConfig::GTK4 PkgConfig::PCRE2 )
    if(APPLE)
      add_test(NAME serial-ui COMMAND serial-ui-test)
      set_tests_properties(serial-ui PROPERTIES TIMEOUT 30)
    endif()
    # Requires a display; run explicitly under tests/headless.py on Linux.
  endif()
endif()
if(BUILD_TESTING AND NOT WIN32)
  foreach(component sequence quick_presets log_model capture plugin)
    string(REPLACE "_" "-" test_name "${component}")
    if(component STREQUAL "plugin")
      set(component_source ${NATIVE_PLUGIN})
    else()
      set(component_source src/${component}.c)
    endif()
    add_executable(native-${test_name}-test tests/${component}_test.c ${component_source} src/payload.c src/settings.c)
    target_include_directories(native-${test_name}-test PRIVATE src)
    target_link_libraries(native-${test_name}-test PRIVATE PkgConfig::GTK4 PkgConfig::PCRE2)
    add_test(NAME native-${test_name} COMMAND native-${test_name}-test)
    set_tests_properties(native-${test_name} PROPERTIES TIMEOUT 30)
  endforeach()
  add_executable(native-transfer-test tests/native_transfer_test.c src/native_bridge.c src/native_serial.c src/transfer.c)
  target_include_directories(native-transfer-test PRIVATE src)
  target_link_libraries(native-transfer-test PRIVATE PkgConfig::GTK4)
  add_test(NAME native-transfer COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/native_transfer_acceptance.py $<TARGET_FILE:native-transfer-test>)
  set_tests_properties(native-transfer PROPERTIES TIMEOUT 120)
endif()
if(BUILD_TESTING AND NOT WIN32)
  add_executable(native-tools-ui-test tests/native_tools_ui_test.c ${NATIVE_TOOLS} src/native_serial.c src/highlighter.c src/payload.c src/settings.c)
  add_dependencies(native-tools-ui-test native-catalog)
  target_include_directories(native-tools-ui-test PRIVATE src)
  target_compile_definitions(native-tools-ui-test PRIVATE TIO_NATIVE_I18N TIO_GUI_VERSION="${PROJECT_VERSION}")
  target_link_libraries(native-tools-ui-test PRIVATE PkgConfig::GTK4 PkgConfig::PCRE2)
  if(APPLE)
    add_test(NAME native-tools-ui COMMAND native-tools-ui-test)
    set_tests_properties(native-tools-ui PROPERTIES TIMEOUT 45)
  endif()
endif()
if(BUILD_TESTING AND NOT WIN32)
  add_executable(native-terminal-test tests/native_terminal_test.c src/native_terminal.c)
  target_include_directories(native-terminal-test PRIVATE src)
  target_link_libraries(native-terminal-test PRIVATE PkgConfig::GTK4)
  if(APPLE)
    add_test(NAME native-terminal COMMAND native-terminal-test)
    set_tests_properties(native-terminal PROPERTIES TIMEOUT 20)
  endif()
endif()
