include(GNUInstallDirs)
include(CTest)
find_package(PkgConfig REQUIRED)
find_package(Gettext REQUIRED)
find_package(Python3 REQUIRED COMPONENTS Interpreter)
pkg_check_modules(GTK4 REQUIRED IMPORTED_TARGET gtk4>=4.12)
pkg_check_modules(PCRE2 REQUIRED IMPORTED_TARGET libpcre2-8)
add_executable(tio-gui WIN32 MACOSX_BUNDLE
  src/serial_main.c src/native_serial.c src/highlighter.c src/payload.c src/settings.c)
target_link_libraries(tio-gui PRIVATE PkgConfig::GTK4 PkgConfig::PCRE2)
if(WIN32)
  pkg_check_modules(NATIVE_PANGO REQUIRED IMPORTED_TARGET pango>=1.56)
  target_link_libraries(tio-gui PRIVATE advapi32 PkgConfig::NATIVE_PANGO)
  if(TIO_GUI_WINDOWS_ICON_RC)
    enable_language(RC)
    target_sources(tio-gui PRIVATE "${TIO_GUI_WINDOWS_ICON_RC}")
  endif()
endif()
if(APPLE)
  target_link_options(tio-gui PRIVATE -Wl,-headerpad_max_install_names)
endif()
foreach(language zh_CN)
  set(mo "${CMAKE_CURRENT_BINARY_DIR}/locale/${language}/LC_MESSAGES/tio-gui.mo")
  add_custom_command(OUTPUT "${mo}"
    COMMAND ${CMAKE_COMMAND} -E make_directory "${CMAKE_CURRENT_BINARY_DIR}/locale/${language}/LC_MESSAGES"
    COMMAND ${GETTEXT_MSGFMT_EXECUTABLE} --check -o "${mo}" "${CMAKE_CURRENT_SOURCE_DIR}/po/${language}.po"
    DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/po/${language}.po" VERBATIM)
  list(APPEND native_catalogs "${mo}")
  install(FILES "${mo}" DESTINATION "${CMAKE_INSTALL_LOCALEDIR}/${language}/LC_MESSAGES")
endforeach()
add_custom_target(native-translations ALL DEPENDS ${native_catalogs})
set(native_catalog "${CMAKE_CURRENT_BINARY_DIR}/native_catalog.h")
add_custom_command(OUTPUT "${native_catalog}"
  COMMAND ${Python3_EXECUTABLE} "${CMAKE_CURRENT_SOURCE_DIR}/scripts/native-catalog.py"
    "${CMAKE_CURRENT_BINARY_DIR}/locale/zh_CN/LC_MESSAGES/tio-gui.mo" "${native_catalog}"
  DEPENDS ${native_catalogs} "${CMAKE_CURRENT_SOURCE_DIR}/scripts/native-catalog.py" VERBATIM)
add_custom_target(native-catalog DEPENDS "${native_catalog}")
include_directories("${CMAKE_CURRENT_BINARY_DIR}")
add_dependencies(tio-gui native-catalog)
target_compile_definitions(tio-gui PRIVATE TIO_GUI_VERSION="${PROJECT_VERSION}")
target_compile_options(tio-gui PRIVATE $<$<C_COMPILER_ID:GNU,Clang,AppleClang>:-Wall;-Wextra;-Wpedantic>)
set_target_properties(tio-gui PROPERTIES
  MACOSX_BUNDLE_BUNDLE_NAME "tio-gui"
  MACOSX_BUNDLE_GUI_IDENTIFIER "io.github.keithxc.tio_gui.serial"
  MACOSX_BUNDLE_BUNDLE_VERSION "${PROJECT_VERSION}"
  MACOSX_BUNDLE_SHORT_VERSION_STRING "${PROJECT_VERSION}")
install(TARGETS tio-gui RUNTIME DESTINATION bin BUNDLE DESTINATION .)
if(BUILD_TESTING)
  add_executable(native-serial-test tests/native_serial_test.c src/native_serial.c)
  target_include_directories(native-serial-test PRIVATE src)
  target_link_libraries(native-serial-test PRIVATE PkgConfig::GTK4)
  if(WIN32)
    target_link_libraries(native-serial-test PRIVATE advapi32)
  endif()
  add_test(NAME native-serial COMMAND native-serial-test)
  set_tests_properties(native-serial PROPERTIES TIMEOUT 30)
  add_executable(payload-test tests/payload_test.c src/payload.c)
  target_include_directories(payload-test PRIVATE src)
  target_link_libraries(payload-test PRIVATE PkgConfig::GTK4)
  add_test(NAME payload COMMAND payload-test)
  add_executable(highlighter-test tests/highlighter_test.c src/highlighter.c)
  target_include_directories(highlighter-test PRIVATE src)
  target_link_libraries(highlighter-test PRIVATE PkgConfig::GTK4)
  add_test(NAME highlighter COMMAND highlighter-test)
  if(NOT WIN32)
    add_executable(serial-ui-test tests/serial_ui_test.c src/native_serial.c src/highlighter.c src/payload.c src/settings.c)
    add_dependencies(serial-ui-test native-catalog)
    target_include_directories(serial-ui-test PRIVATE src)
    target_compile_definitions(serial-ui-test PRIVATE TIO_GUI_VERSION="${PROJECT_VERSION}")
    target_link_libraries(serial-ui-test PRIVATE PkgConfig::GTK4 PkgConfig::PCRE2)
    if(APPLE)
      add_test(NAME serial-ui COMMAND serial-ui-test)
      set_tests_properties(serial-ui PROPERTIES TIMEOUT 30)
    endif()
    # Requires a display; run explicitly under tests/headless.py on Linux.
  endif()
endif()
